project:
  type: book

book:
  title: "Python para OSINT em 21 dias"
  author: "Norah Jones"
  date: "04/10/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - pag2.qmd
    - pag3.qmd
    - pag4.qmd
    - pag5.qmd
    - pag6.qmd
    - pag7.qmd
    - pag8.qmd
    - pag9.qmd
    - pag10.qmd
    - pag11.qmd
    - pag12.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

